### ISSUE TITLE
Arg 'total_fee' for BCApi.pay should support 'long' type

### ISSUE THREAD

**Issue by aiden0z** [beecloud/beecloud-python#1]
Now the BCApi.pay only accpet total_fee with instance of type `int`, it should also accept the instance of  type `long`.  Excample code:

```
if not isinstance(total_fee, (int, long))  or not instance(total_fee, or total_fee < 0:
            return self.param_invalid('total_fee', 'total_fee以分为单位，为正整数')
```

**Comment by josephgao** [comment]
sorry, cause beecloud-api needs int. If using long, the json string would end with 'l'.

**Comment by josephgao** [comment]
see https://github.com/beecloud/beecloud-rest-api/blob/master/online/README.md

**Comment by Danzeer** [comment]
And also, it's big enough (2^31-1 = 2 147 483 647 => 2 147 483 6.47 RMB)
 for each payment.

**Comment by quietbamboo** [comment]
OK, keep the way as it is. I think it's fine to require that total_fee is int.
